// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkMark': string;
  'checkMarkWrapper': string;
  'form': string;
  'formButton': string;
  'formField': string;
  'formText': string;
  'formTextButton': string;
}
export const cssExports: CssExports;
export default cssExports;
