// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'formButton': string;
  'formField': string;
}
export const cssExports: CssExports;
export default cssExports;
