// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'line': string;
  'tabs': string;
  'tabsItem': string;
  'tabsItemActive': string;
  'tabsItemCount': string;
  'tabsItemCount__active': string;
  'tabsItemText': string;
}
export const cssExports: CssExports;
export default cssExports;
