// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'input': string;
  'inputFocus': string;
  'inputTitle': string;
  'inputTitleActive': string;
  'inputWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
