// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'textarea': string;
  'textareaFocus': string;
  'textareaTitle': string;
  'textareaTitleActive': string;
  'textareaWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
