// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'asideMenu': string;
  'asidePreview': string;
  'asidePreviewWrapper': string;
  'loader': string;
  'manga': string;
  'mangaDescription': string;
  'mangaImage': string;
  'mangaTitle': string;
  'mangaWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
