// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	button: string
	error: string
	form: string
	headerWrapper: string
	input: string
	inputFile: string
	inputFileLabel: string
	inputWrapper: string
	photo: string
	photoCross: string
	photoList: string
	photoName: string
	photoNumber: string
	profileWrapper: string
	profileWrapperTitle: string
}

export const cssExports: CssExports
export default cssExports
