// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'error': string;
  'form': string;
  'input': string;
  'inputFile': string;
  'inputWrapper': string;
  'photo': string;
  'photoCross': string;
  'photoList': string;
  'photoName': string;
  'photoNumber': string;
  'photoWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
